### ISSUE TITLE
Cannot read property 'getComponent' of undefined 

### ISSUE THREAD

**Issue by Alex61NN5** [didacte/videojs-vimeo#2]
Hey there Im trying to use this in my project and I am getting this error

    Uncaught TypeError: Cannot read property 'getComponent' of undefined
        at Object.<anonymous> (videojs-vimeo.js:2069)
        at Object.2.@vimeo/player (videojs-vimeo.js:2349)
        at s (videojs-vimeo.js:7)
        at e (videojs-vimeo.js:7)
        at videojs-vimeo.js:7
        at videojs-vimeo.js:7
        at videojs-vimeo.js:7

I have inserted both the videojs and videovimeo.js at the bottom of my html like so..

    <script src="./assets/videojs-vimeo-master/dist/videojs-vimeo.js"></script>
    <script src="http://vjs.zencdn.net/6.6.3/video.js"></script>

and In my html I just copied what was used in the example

    <video
        id="vid1"
        class="video-js"
        width="640" height="264"
        data-setup='{ "techOrder": ["vimeo"], "sources": [{ "type": "video/vimeo", "src": "https://vimeo.com/248409603"}] }'
     >
    </video>

Thanks

**Comment by jbourassa** [comment]
Hey Alex,

This repository was pretty much only used to develop the plugin, it has since been merged in the official videojs plugin: https://github.com/videojs/videojs-vimeo

Please use that version, and if you're having the same issue, feel free to open an issue there.

Best,
